### PR TITLE
fix: ci docker build

### PR DESCRIPTION
**Pull request by Freyskeyd**
# Description

Fixing the CI docker build

## PR Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added or updated tests that comprehensively prove my change is effective or that my feature works

### CODE REVIEW

**Comment by atanmarko** [comment]
I don't really understand the changes here, I think better for tools team to review it

**Review by sebastiendan — APPROVED** [review]
Approved, but would be great to have clear descriptions to understand what the issue was and how the fix solved the problem.

**Review by gruberb — APPROVED** [review]
I think I removed the `Extract metadata` in my last PR. I thought we don't need it anymore. Sorry! 

The `broadcast_channel` I assume is just a cleanup?

**Review by dvdplm — APPROVED** [review]

**Comment by dvdplm** [comment]
@Freyskeyd CI seems angry but it's not clear (to me) what the problem is. :/

**Pull request merged**
